apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gwrs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gwrs
    app.kubernetes.io/part-of: ci10t-786-0086-app
  name: devfile-sample-gwrs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gwrs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gwrs
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0086-tenant/ci10t-786-0086-app/devfile-sample-gwrs@sha256:38b1f486844da8e1355da13473ec607fdd0d3be651c4bd2427a669b72b6cb72d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
